### ISSUE TITLE
Add a QT like table widget

### ISSUE THREAD

**Issue by ufechner7** [Clemapfel/mousetrap.jl#19] opened 2023-08-26 16:20 UTC
QT has a nice table widget, similar to an Excel table: https://doc.qt.io/qt-6/qtablewidget.html

Would it be possible to add something like this (high level) to mousetrap?

Perhaps allowing to scroll through a DataFrame?

**Comment by Clemapfel** [comment] 2023-08-26 16:39
Mousetrap has `ColumnView` which, to my knowledge, has feature parity with `QtTableWidget`, except it doesn't use the model-view pattern, you have to manually insert a widget for each cell. It does support rows, named columns, and selections, each cell can contain any other widget. See [here](https://clemens-cords.com/mousetrap/01_manual/04_widgets/#Column-View) for how to use it, and [here](https://clemens-cords.com/mousetrap/02_library/classes/#Functions-that-operate-on-this-type:-18) for a list of all its features.

Also does this mean mousetrap is working for you now? I've been trying to reproduce #11 but have been unable to do so, I also [asked on the GNOME discourse](https://discourse.gnome.org/t/gdk-x11-surface-get-xid-hard-crashes-on-ubuntu-22-04/16818) but have gotten no response, probably because no one there knows what could be going on either.

**Comment by ufechner7** [comment] 2023-08-26 17:27
> Also does this mean mousetrap is working for you now?

No, on Ubuntu it does not work yet.

**Comment by Clemapfel** [comment] 2023-08-26 17:44
I'm sorry you're having trouble, I will continue looking into it then.

Looking at the QT table again one more difference is that `ColumnView` does not have named rows, only columns, though you can just add one extra column on the left and fill it with labels, which will look the same.

I do think `ColumnView` does fit your description so I will close this issue.

**Closed by Clemapfel** 2023-08-26 17:44 UTC
Labels: Help, Acknowledged
