### ISSUE TITLE
Installation precompilation issue

### ISSUE THREAD

**Issue by mpeters2** [Clemapfel/Mousetrap.jl#52] opened 2024-01-01 22:15 UTC
Julia 1.10
MacOS 14
ARM64

during installation, I get this error out the end.
```
Precompiling project...
  64 dependencies successfully precompiled in 26 seconds. 171 already precompiled.
  1 dependency had output during precompilation:
┌ Mousetrap
│  (process:37545): Core OpenGL-CRITICAL **: 17:09:54.252: ../gdk/macos/gdkmacosglcontext.c:408: invalid share context
│  
│  (process:37545): mousetrap-WARNING **: 17:09:54.252: In gdk_gl_context_realize:invalid share context
│  
│  (process:37545): mousetrap-CRITICAL **: 17:09:54.252: In initialize_opengl: Unable to create global OpenGL context, disabling the `RenderArea` widget
└  
```

I tried to install Mousetrap using this workflow:

```
import Pkg;
begin
  Pkg.add(url="https://github.com/clemapfel/mousetrap_jll")
  Pkg.add(url="https://github.com/clemapfel/mousetrap.jl")
end
```

**Comment by Clemapfel** [comment] 2024-01-02 16:21
Duplicate of #34 

See [here](https://github.com/Clemapfel/Mousetrap.jl/issues/25#issuecomment-1731349366) for how to disable the warning. The ARM macs are a huge issue and I have no way to debug this without owning a physical machine, so for now the warning disabling the `RenderArea` widget is expected behavior.

**Closed by Clemapfel** 2024-01-02 16:21 UTC
Labels: Duplicate, Acknowledged
